### ISSUE TITLE
Catch those errors!

### ISSUE THREAD

**Issue by jeroentvb** [BasPieren/web-app-from-scratch-18-19#1]
Handle all your error's!

The [following bit](https://github.com/BasPieren/web-app-from-scratch-18-19/blob/master/week1/public/js/app.js#L33-L35) uses your `getData()` function. All looks well, except you don't catch the error, may the promise ever return one.

You should change this:
```js
getData.then(function(data){
    renderData(data)
  })
```

To this:
```js
getData
  .then(function(data){
    renderData(data)
  })
  .catch(function(error){
    console.log(error)
  })
```

To make it smaller and easier to read (in my opinion), you could also apply arrow functions (this goes for all anonymous functions in your project).

```js
getData
  .then(data => renderData(data))
  .catch(error => console.log(error))
```

**Comment by maanlamp** [comment]
@jeroentvb Don't **console**._log_ your errors, use the proper **console**._error_ method instead :)

**Comment by jeroentvb** [comment]
Whoops..
Little fast with that one. I agree, use `console.error()` instead :)
