### ISSUE TITLE
Typo 'response' in readme

### ISSUE THREAD

**Issue by deannabosschert** [BasPieren/web-app-from-scratch-18-19#9]
Fetching API Data
I make use of fetch() to get back data using https://swapi.co/api/films/ as endpoint. First we parse the response we get from the API to JSON. After that we render the data using the renderData function. If an error occurs at any point we catch it and send an error message using console.error().

function getData() {
  fetch('https://swapi.co/api/films/')
    .then(**respone** => {
      return **respone**.json()
    })
    .then(data => {
      renderData(data)
    })
    .catch(error => console.error(error))
}

Zag 'm toen Laurens je readme liet zien, dunno of je het al had aangepast in je code zelf
respone ipv response

**Comment by BasPieren** [comment]
Typo is fixed. 👍🏻
